# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
#      - image: maven/3.6.0-jdk-8
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/postgres:9.6
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: test
          POSTGRES_PASSWORD: "test"

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
#      MAVEN_OPTS: -Xmx2600m
      pg_url: jdbc:postgresql://localhost/test?currentSchema=public&username=circleci&password=test
      CODECOV_TOKEN: 48e19fae-3c35-4c56-9297-8620e6808cc9
      MAVEN_OPTS: "-Xmx512M"
      JAVA_OPTS: "-Xms512M -Xmx512M"
      _JAVA_OPTIONS : "-Xms512M -Xmx512M"
    
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

#      - run: 
#          name: Resolve external deps
#          command: mvn dependency:resolve
#

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

        
      # run tests!
      - run: 
          name: FullTest
          command: |
            mvn --version
            mvn -B clean install jacoco:report -DrepoToken=sMBbBcjrybuhdwKHFC61BvBU5y4oAjNEt -Dpg_url=$pg_url
            bash <(curl -s https://codecov.io/bash)

      - run: 
          name: Remove factcast artifacts from local repo
          command: rm ~/.m2/repository/org/factcast -rf

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
