name: Format

on:
  push:
    pull_request: [ master ]

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # v2 minimum required
        with:
          token: ${{ secrets.PAT }}
      - uses: actions/setup-java@v1
        with:
          # Recommended: latest versions of Google Java Format require JDK 11+
          distribution: "coretto"
          java-version: "11"
      - run: ./mvnw -B spotless:apply --file pom.xml
      # commit possible changes after applying formatter
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply formatter
